name: Build and Run Local Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask app
      run: python app.py

    - name: Forward traffic to local server
      uses: w9jds/ngrok-action@v1.1.0
      with:
        authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
        region: us
        proto: http
        port: 5000
